# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pupbook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pupbook
	pod 'Parse'
    	pod 'AlamofireImage'
  target 'PupbookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PupbookUITests' do
    # Pods for testing
  end

end
